apiVersion: apps/v1
kind: Deployment

metadata:
  name: cockpit
  namespace: credentialing

spec:
  replicas: 1

  selector:
    matchLabels:
      app: cockpit

  template:
    metadata:
      labels:
        app: cockpit

    spec:
      automountServiceAccountToken: false
      containers:
        - name: cockpit
          image: credentialing-cockpit:local

          ports:
            - containerPort: 8004

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 512Mi

          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 30
            periodSeconds: 20