apiVersion: v1
kind: Service

metadata:
  name: excel-api
  namespace: credentialing

spec:
  selector:
    app: excel-api

  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002

  type: ClusterIP